services:
  wud:
    image: getwud/wud:latest
    container_name: wud
    restart: always
    environment:
      - WUD_LOG_LEVEL=${WUD_LOG_LEVEL}
      - WUD_WATCHER_LOCAL_CRON=${WUD_WATCHER_LOCAL_CRON}
      - WUD_WATCHER_LOCAL_WATCHBYDEFAULT=${WUD_WATCHER_LOCAL_WATCHBYDEFAULT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/store
    ports:
      - "${LAN_IP}:3069:3000"
    networks:
      - proxy

networks:
  proxy:
    external: true
