services:
  matomo:
    image: matomo:latest
    container_name: matomo
    restart: always
    environment:
      - MATOMO_DATABASE_HOST=${MATOMO_DATABASE_HOST}
      - MATOMO_DATABASE_ADAPTER=${MATOMO_DATABASE_ADAPTER}
      - MATOMO_DATABASE_TABLES_PREFIX=${MATOMO_DATABASE_TABLES_PREFIX}
      - MATOMO_DATABASE_USERNAME=${MATOMO_DATABASE_USERNAME}
      - MATOMO_DATABASE_PASSWORD=${MATOMO_DATABASE_PASSWORD}
      - MATOMO_DATABASE_DBNAME=${MATOMO_DATABASE_DBNAME}
    volumes:
      - ./data:/var/www/html
    ports:
      - "${MATOMO_PORT}:80"
    networks:
      - proxy

networks:
  proxy:
    external: true
