services:
  matomo:
    image: matomo:latest
    container_name: matomo
    restart: always
    environment:
      - MATOMO_DATABASE_HOST=mariadb
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=matomo_secure_password
      - MATOMO_DATABASE_DBNAME=matomo
    volumes:
      - ./data:/var/www/html
    ports:
      - "8090:80"
    networks:
      - proxy

networks:
  proxy:
    external: true
